import {Country} from '@domain';

export const countries: Country[] = [
  {iso: 'AD', name: 'Andorra'},
  {iso: 'AE', name: 'Emirados Árabes Unidos'},
  {iso: 'AF', name: 'Afeganistão'},
  {iso: 'AG', name: 'Antígua e Barbuda'},
  {iso: 'AI', name: 'Anguilla'},
  {iso: 'AL', name: 'Albânia'},
  {iso: 'AM', name: 'Armênia'},
  {iso: 'AO', name: 'Angola'},
  {iso: 'AR', name: 'Argentina'},
  {iso: 'AS', name: 'Samoa Americana'},
  {iso: 'AT', name: 'Áustria'},
  {iso: 'AU', name: 'Austrália'},
  {iso: 'AW', name: 'Aruba'},
  {iso: 'AX', name: 'Ilhas Aland'},
  {iso: 'AZ', name: 'Azerbaijão'},
  {iso: 'BA', name: 'Bósnia e Herzegovina'},
  {iso: 'BB', name: 'Barbados'},
  {iso: 'BD', name: 'Bangladesh'},
  {iso: 'BE', name: 'Bélgica'},
  {iso: 'BF', name: 'Burquina Faso'},
  {iso: 'BG', name: 'Bulgária'},
  {iso: 'BH', name: 'Bahrein'},
  {iso: 'BI', name: 'Burundi'},
  {iso: 'BJ', name: 'Benin'},
  {iso: 'BL', name: 'São Bartolomeu'},
  {iso: 'BM', name: 'Bermudas'},
  {iso: 'BN', name: 'Brunei'},
  {iso: 'BO', name: 'Bolívia'},
  {iso: 'BQ', name: 'Bonaire, Santo Eustáquio e Saba'},
  {iso: 'BR', name: 'Brasil'},
  {iso: 'BS', name: 'Bahamas'},
  {iso: 'BT', name: 'Butão'},
  {iso: 'BW', name: 'Botsuana'},
  {iso: 'BY', name: 'Bielorrússia'},
  {iso: 'BZ', name: 'Belize'},
  {iso: 'CA', name: 'Canadá'},
  {iso: 'CC', name: 'Ilhas Cocos (Keeling)'},
  {iso: 'CD', name: 'República Democrática do Congo'},
  {iso: 'CF', name: 'República Centro-Africana'},
  {iso: 'CG', name: 'República do Congo'},
  {iso: 'CH', name: 'Suíça'},
  {iso: 'CI', name: 'Costa do Marfim'},
  {iso: 'CK', name: 'Ilhas Cook'},
  {iso: 'CL', name: 'Chile'},
  {iso: 'CM', name: 'Camarões'},
  {iso: 'CN', name: 'China'},
  {iso: 'CO', name: 'Colômbia'},
  {iso: 'CR', name: 'Costa Rica'},
  {iso: 'CU', name: 'Cuba'},
  {iso: 'CV', name: 'Cabo Verde'},
  {iso: 'CW', name: 'Curaçao'},
  {iso: 'CX', name: 'Ilha Christmas'},
  {iso: 'CY', name: 'Chipre'},
  {iso: 'CZ', name: 'República Tcheca'},
  {iso: 'DE', name: 'Alemanha'},
  {iso: 'DJ', name: 'Djibuti'},
  {iso: 'DK', name: 'Dinamarca'},
  {iso: 'DM', name: 'Dominica'},
  {iso: 'DO', name: 'República Dominicana'},
  {iso: 'DZ', name: 'Argélia'},
  {iso: 'EC', name: 'Equador'},
  {iso: 'EE', name: 'Estônia'},
  {iso: 'EG', name: 'Egito'},
  {iso: 'EH', name: 'Saara Ocidental'},
  {iso: 'ER', name: 'Eritreia'},
  {iso: 'ES', name: 'Espanha'},
  {iso: 'ET', name: 'Etiópia'},
  {iso: 'FI', name: 'Finlândia'},
  {iso: 'FJ', name: 'Fiji'},
  {iso: 'FK', name: 'Ilhas Malvinas'},
  {iso: 'FM', name: 'Estados Federados da Micronésia'},
  {iso: 'FO', name: 'Ilhas Faroé'},
  {iso: 'FR', name: 'França'},
  {iso: 'GA', name: 'Gabão'},
  {iso: 'GB', name: 'Reino Unido'},
  {iso: 'GD', name: 'Granada'},
  {iso: 'GE', name: 'Geórgia'},
  {iso: 'GF', name: 'Guiana Francesa'},
  {iso: 'GG', name: 'Guernsey'},
  {iso: 'GH', name: 'Gana'},
  {iso: 'GI', name: 'Gibraltar'},
  {iso: 'GL', name: 'Gronelândia'},
  {iso: 'GM', name: 'Gâmbia'},
  {iso: 'GN', name: 'Guiné'},
  {iso: 'GP', name: 'Guadalupe'},
  {iso: 'GQ', name: 'Guiné Equatorial'},
  {iso: 'GR', name: 'Grécia'},
  {iso: 'GT', name: 'Guatemala'},
  {iso: 'GU', name: 'Guam'},
  {iso: 'GW', name: 'Guiné-Bissau'},
  {iso: 'GY', name: 'Guiana'},
  {iso: 'HK', name: 'Hong Kong'},
  {iso: 'HN', name: 'Honduras'},
  {iso: 'HR', name: 'Croácia'},
  {iso: 'HT', name: 'Haiti'},
  {iso: 'HU', name: 'Hungria'},
  {iso: 'ID', name: 'Indonésia'},
  {iso: 'IE', name: 'Irlanda'},
  {iso: 'IL', name: 'Israel'},
  {iso: 'IM', name: 'Ilha de Man'},
  {iso: 'IN', name: 'Índia'},
  {iso: 'IO', name: 'Território Britânico do Oceano Índico'},
  {iso: 'IQ', name: 'Iraque'},
  {iso: 'IR', name: 'Irã'},
  {iso: 'IS', name: 'Islândia'},
  {iso: 'IT', name: 'Itália'},
  {iso: 'JE', name: 'Jersey'},
  {iso: 'JM', name: 'Jamaica'},
  {iso: 'JO', name: 'Jordânia'},
  {iso: 'JP', name: 'Japão'},
  {iso: 'KE', name: 'Quênia'},
  {iso: 'KG', name: 'Quirguistão'},
  {iso: 'KH', name: 'Camboja'},
  {iso: 'KI', name: 'Quiribati'},
  {iso: 'KM', name: 'Comores'},
  {iso: 'KN', name: 'São Cristóvão e Nevis'},
  {iso: 'KP', name: 'Coreia do Norte'},
  {iso: 'KR', name: 'Coreia do Sul'},
  {iso: 'KW', name: 'Kuwait'},
  {iso: 'KY', name: 'Ilhas Cayman'},
  {iso: 'KZ', name: 'Cazaquistão'},
  {iso: 'LA', name: 'Laos'},
  {iso: 'LB', name: 'Líbano'},
  {iso: 'LC', name: 'Santa Lúcia'},
  {iso: 'LI', name: 'Liechtenstein'},
  {iso: 'LK', name: 'Sri Lanka'},
  {iso: 'LR', name: 'Libéria'},
  {iso: 'LS', name: 'Lesoto'},
  {iso: 'LT', name: 'Lituânia'},
  {iso: 'LU', name: 'Luxemburgo'},
  {iso: 'LV', name: 'Letônia'},
  {iso: 'LY', name: 'Líbia'},
  {iso: 'MA', name: 'Marrocos'},
  {iso: 'MC', name: 'Mônaco'},
  {iso: 'MD', name: 'Moldávia'},
  {iso: 'ME', name: 'Montenegro'},
  {iso: 'MF', name: 'São Martinho'},
  {iso: 'MG', name: 'Madagascar'},
  {iso: 'MH', name: 'Ilhas Marshall'},
  {iso: 'MK', name: 'Macedônia do Norte'},
  {iso: 'ML', name: 'Mali'},
  {iso: 'MM', name: 'Mianmar'},
  {iso: 'MN', name: 'Mongólia'},
  {iso: 'MO', name: 'Macau'},
  {iso: 'MP', name: 'Ilhas Marianas do Norte'},
  {iso: 'MQ', name: 'Martinica'},
  {iso: 'MR', name: 'Mauritânia'},
  {iso: 'MS', name: 'Montserrat'},
  {iso: 'MT', name: 'Malta'},
  {iso: 'MU', name: 'Maurício'},
  {iso: 'MV', name: 'Maldivas'},
  {iso: 'MW', name: 'Malaui'},
  {iso: 'MX', name: 'México'},
  {iso: 'MY', name: 'Malásia'},
  {iso: 'MZ', name: 'Moçambique'},
  {iso: 'NA', name: 'Namíbia'},
  {iso: 'NC', name: 'Nova Caledônia'},
  {iso: 'NE', name: 'Níger'},
  {iso: 'NF', name: 'Ilha Norfolk'},
  {iso: 'NG', name: 'Nigéria'},
  {iso: 'NI', name: 'Nicarágua'},
  {iso: 'NL', name: 'Países Baixos'},
  {iso: 'NO', name: 'Noruega'},
  {iso: 'NP', name: 'Nepal'},
  {iso: 'NR', name: 'Nauru'},
  {iso: 'NU', name: 'Niue'},
  {iso: 'NZ', name: 'Nova Zelândia'},
  {iso: 'OM', name: 'Omã'},
  {iso: 'PA', name: 'Panamá'},
  {iso: 'PE', name: 'Peru'},
  {iso: 'PF', name: 'Polinésia Francesa'},
  {iso: 'PG', name: 'Papua-Nova Guiné'},
  {iso: 'PH', name: 'Filipinas'},
  {iso: 'PK', name: 'Paquistão'},
  {iso: 'PL', name: 'Polônia'},
  {iso: 'PM', name: 'São Pedro e Miquelão'},
  {iso: 'PR', name: 'Porto Rico'},
  {iso: 'PS', name: 'Palestina'},
  {iso: 'PT', name: 'Portugal'},
  {iso: 'PW', name: 'Palau'},
  {iso: 'PY', name: 'Paraguai'},
  {iso: 'QA', name: 'Catar'},
  {iso: 'RE', name: 'Reunião'},
  {iso: 'RO', name: 'Romênia'},
  {iso: 'RS', name: 'Sérvia'},
  {iso: 'RU', name: 'Rússia'},
  {iso: 'RW', name: 'Ruanda'},
  {iso: 'SA', name: 'Arábia Saudita'},
  {iso: 'SB', name: 'Ilhas Salomão'},
  {iso: 'SC', name: 'Seicheles'},
  {iso: 'SD', name: 'Sudão'},
  {iso: 'SE', name: 'Suécia'},
  {iso: 'SG', name: 'Singapura'},
  {iso: 'SH', name: 'Santa Helena, Ascensão e Tristão da Cunha'},
  {iso: 'SI', name: 'Eslovênia'},
  {iso: 'SJ', name: 'Svalbard e Jan Mayen'},
  {iso: 'SK', name: 'Eslováquia'},
  {iso: 'SL', name: 'Serra Leoa'},
  {iso: 'SM', name: 'San Marino'},
  {iso: 'SN', name: 'Senegal'},
  {iso: 'SO', name: 'Somália'},
  {iso: 'SR', name: 'Suriname'},
  {iso: 'SS', name: 'Sudão do Sul'},
  {iso: 'ST', name: 'São Tomé e Príncipe'},
  {iso: 'SV', name: 'El Salvador'},
  {iso: 'SX', name: 'São Martinho (Parte Holandesa)'},
  {iso: 'SY', name: 'Síria'},
  {iso: 'SZ', name: 'Essuatíni'},
  {iso: 'TA', name: 'Tristão da Cunha'},
  {iso: 'TC', name: 'Ilhas Turcas e Caicos'},
  {iso: 'TD', name: 'Chade'},
  {iso: 'TG', name: 'Togo'},
  {iso: 'TH', name: 'Tailândia'},
  {iso: 'TJ', name: 'Tajiquistão'},
  {iso: 'TK', name: 'Toquelau'},
  {iso: 'TL', name: 'Timor-Leste'},
  {iso: 'TM', name: 'Turcomenistão'},
  {iso: 'TN', name: 'Tunísia'},
  {iso: 'TO', name: 'Tonga'},
  {iso: 'TR', name: 'Turquia'},
  {iso: 'TT', name: 'Trinidad e Tobago'},
  {iso: 'TV', name: 'Tuvalu'},
  {iso: 'TW', name: 'Taiwan'},
  {iso: 'TZ', name: 'Tanzânia'},
  {iso: 'UA', name: 'Ucrânia'},
  {iso: 'UG', name: 'Uganda'},
  {iso: 'US', name: 'Estados Unidos'},
  {iso: 'UY', name: 'Uruguai'},
  {iso: 'UZ', name: 'Uzbequistão'},
  {iso: 'VA', name: 'Vaticano'},
  {iso: 'VC', name: 'São Vicente e Granadinas'},
  {iso: 'VE', name: 'Venezuela'},
  {iso: 'VG', name: 'Ilhas Virgens Britânicas'},
  {iso: 'VI', name: 'Ilhas Virgens Americanas'},
  {iso: 'VN', name: 'Vietnã'},
  {iso: 'VU', name: 'Vanuatu'},
  {iso: 'WF', name: 'Wallis e Futuna'},
  {iso: 'WS', name: 'Samoa'},
  {iso: 'XK', name: 'Kosovo'},
  {iso: 'YE', name: 'Iêmen'},
  {iso: 'YT', name: 'Mayotte'},
  {iso: 'ZA', name: 'África do Sul'},
  {iso: 'ZM', name: 'Zâmbia'},
  {iso: 'ZW', name: 'Zimbábue'},
];
